package com.myspace.sla_test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class datos implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer datos;

	public datos() {
	}

	public java.lang.Integer getDatos() {
		return this.datos;
	}

	public void setDatos(java.lang.Integer datos) {
		this.datos = datos;
	}

	public datos(java.lang.Integer datos) {
		this.datos = datos;
	}

}