package com.myspace.sla_test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class datos implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public datos() {
    }


}